### ISSUE TITLE
{Lucas Bretas} (SJC - SP)  { Frontend Dev em construção}

### ISSUE THREAD

**Issue by devlucasbretas** [novofuturo/quero-emprego#6]
Me chamo Lucas Bretas, tenho 24 anos e busco uma oportunidade de transição  de carreira, na verdade busco a oportunidade de trabalhar com o que eu sempre gostei gostei. Venho aprendendo as tecnologias de front end : Html5, css3 e Js, programo de forma iniciante buscando aprender mais a cada dia.

**Comment by PauloLuan** [comment]
Massa @lucasfront ! Obrigado pela disponibilidade em criar a Issue do seu perfil, só peço que você crie a Issue seguindo o padrão do template que deixei na criação, é só você clicar em 'New Issue' e clicar no botão verde de 'Get Started'

![image](https://user-images.githubusercontent.com/1131963/102781750-f923b180-4376-11eb-9079-af8227dbc349.png)

**Comment by devlucasbretas** [comment]
Muito obrigado pelo toque, é  que ainda não  sei nada de github mas agora refiz seguindo o template.. valeu mesmo.

Obter o Outlook para Android<https://aka.ms/ghei36>
________________________________
